# Generated by Django 5.1.1 on 2024-10-19 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInformation',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=45, null=True)),
                ('house_no', models.CharField(blank=True, max_length=45, null=True)),
                ('province', models.CharField(blank=True, max_length=45, null=True)),
                ('barangay', models.CharField(blank=True, max_length=45, null=True)),
                ('street_village', models.CharField(blank=True, max_length=45, null=True)),
                ('city_municipality', models.CharField(blank=True, max_length=45, null=True)),
                ('state', models.CharField(blank=True, max_length=45, null=True)),
                ('zipcode', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=45, null=True)),
                ('mobile_number', models.BigIntegerField(blank=True, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'account_information',
            },
        ),
        migrations.CreateModel(
            name='AccountStorage',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=45, null=True)),
                ('account_status', models.CharField(blank=True, max_length=11, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountinformation')),
            ],
            options={
                'db_table': 'account_storage',
            },
        ),
        migrations.CreateModel(
            name='InterviewStorage',
            fields=[
                ('interview_applicant_id', models.AutoField(primary_key=True, serialize=False)),
                ('interview_schedule_date', models.DateField(blank=True, null=True)),
                ('interviewer_schedule_status', models.CharField(blank=True, max_length=10, null=True)),
                ('applicant_schedule_date', models.DateField(blank=True, null=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('interviewer_feedback', models.TextField(blank=True, null=True)),
                ('interviewer_feedback_status', models.CharField(blank=True, max_length=20, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountinformation')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountstorage')),
            ],
            options={
                'db_table': 'interview_storage',
            },
        ),
        migrations.CreateModel(
            name='JobDetailsAndRequirements',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('job_company', models.CharField(blank=True, max_length=50, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('job_benefits', models.TextField(blank=True, null=True)),
                ('job_requirements', models.TextField(blank=True, null=True)),
                ('job_status', models.CharField(blank=True, max_length=7, null=True)),
                ('job_date_published', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountinformation')),
            ],
            options={
                'db_table': 'job_details_and_requirements',
            },
        ),
        migrations.CreateModel(
            name='ListOfApplicantsWithStatusAndCredentials',
            fields=[
                ('applicant_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_status', models.CharField(blank=True, max_length=30, null=True)),
                ('credentials', models.BinaryField(blank=True, null=True)),
                ('file_metadata', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountinformation')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.interviewstorage')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.jobdetailsandrequirements')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountstorage')),
            ],
            options={
                'db_table': 'list_of_applicants_with_status_and_credentials',
            },
        ),
    ]
