# Generated by Django 5.1.1 on 2024-12-28 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanihire_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewstorage',
            name='admin_message',
        ),
        migrations.RemoveField(
            model_name='interviewstorage',
            name='applicant_schedule_date',
        ),
        migrations.RemoveField(
            model_name='interviewstorage',
            name='interviewer_feedback',
        ),
        migrations.RemoveField(
            model_name='interviewstorage',
            name='interviewer_feedback_status',
        ),
        migrations.RemoveField(
            model_name='interviewstorage',
            name='interviewer_schedule_status',
        ),
        migrations.RemoveField(
            model_name='listofapplicantswithstatusandcredentials',
            name='interview',
        ),
        migrations.AddField(
            model_name='interviewstorage',
            name='interviewer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listofapplicantswithstatusandcredentials',
            name='admin_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofapplicantswithstatusandcredentials',
            name='applicant_schedule_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofapplicantswithstatusandcredentials',
            name='interview_applicant_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.interviewstorage'),
        ),
        migrations.AddField(
            model_name='listofapplicantswithstatusandcredentials',
            name='interviewer_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listofapplicantswithstatusandcredentials',
            name='interviewer_feedback_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
