# Generated by Django 5.1.1 on 2024-12-31 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bayanihire_app', '0003_otpverification'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bayanihire_app.accountinformation'),
        ),
    ]
